MODULES = [
    {
        "module_id": "s3-static-site",
        "name": "S3 Static Site",
        "project": "terraform-static-website",
        "iac_tool": "Terraform",
        "category": "Storage",
        "difficulty": "Beginner",
        "aws_services": ["S3", "CloudFront", "IAM"],
        "service_features": [
            "Private S3 bucket",
            "CloudFront distribution",
            "Origin Access Control",
            "S3 bucket policy",
            "Server-side encryption",
            "Versioning",
        ],
        "use_cases": [
            "Static websites",
            "Documentation sites",
            "Portfolio sites",
            "Low-cost frontend hosting",
        ],
        "description": "Private S3 bucket with CloudFront delivery.",
        "status": "Published",
    },
    {
        "module_id": "serverless-api",
        "name": "Serverless Catalogue API",
        "project": "terraform-catalogue-api",
        "iac_tool": "Terraform",
        "category": "Serverless",
        "difficulty": "Beginner",
        "aws_services": ["API Gateway", "Lambda", "DynamoDB", "IAM", "CloudWatch"],
        "service_features": [
            "HTTP API",
            "Lambda proxy integration",
            "DynamoDB table",
            "CloudWatch log group",
            "Least-privilege IAM policy",
        ],
        "use_cases": [
            "Low-cost APIs",
            "Event-driven backends",
            "Read-only catalogue APIs",
            "Serverless prototypes",
        ],
        "description": "Serverless API backed by Lambda and DynamoDB.",
        "status": "Published",
    },
]
